### ISSUE TITLE
Vorschau ist überbelichtet

### ISSUE THREAD

**Issue by Jasmin129** [SitePointYves/IssueTracker#4]
Obwohl keine weiteren Lichter in dem Raum sind, wird selbst bei einer Gesamthelligkeit von 0.1 alles sehr hell angezeigt. Der Fehler trat nach dem Ein- und Ausschalten von dem Directionalen Licht im Startknoten auf.

**Comment by SitePointYves** [comment]
wegen ambientlight 1 in editoren
Möglichekit toggle natural light

**Comment by Jasmin129** [comment]
Wenn die grundlegende Helligkeit auf 0.1 steht, ist alles viel Heller als bei einer Helligkeit von 1.
